### ISSUE TITLE
Add GitHub token

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/homebrew-brew#13]
This PR got rate limited to hell: https://github.com/paradigmxyz/homebrew-brew/pull/12

Need to figure out what perms the token needs

**Comment by tadeongmi** [comment]
I'm using GitHub token, maybe that's why the binary install is failing?

```
Caused by:
  failed to fetch into: /Users/user/Library/Caches/Homebrew/cargo_cache/git/db/uint-10eb28276571b47e

Caused by:
  failed to authenticate when downloading repository

  * attempted to find username/password via git's `credential.helper` support, but failed

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  failed to acquire username/password from local configuration

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/paradigmxyz/homebrew-brew/issues
```

**Comment by onbjerg** [comment]
Hi, this is unrelated - not sure why you fail to install, it is something on your end. This issue is for the workflow in this repository specifically.

What are you trying to install?

**Comment by tadeongmi** [comment]
`brew install paradigmxyz/brew/reth`

I granted it access to keychain for github credentials but something seemed to not work (I'm still using normal github token credentials to pull and push on other work)

**Comment by onbjerg** [comment]
Sorry, I lost track of this issue. Did you eventually figure it out? It looks like it's a dependency that failed to download, most likely because it was pinned to a commit that no longer exists. I'd update the tap and try again.
